<?php

namespace ContactsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    
    public function findAllByName()
        {
            return $this->findBy(array(), array('name' => 'ASC'));
        }

    public function findPersonByName($string){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM ContactsBundle:Person p WHERE p.name LIKE :name");
        $query->setParameter("name", $string."%");
        $find = $query->getResult();
        return $find;
    }
    
    
}
